export enum Type {
  DINE_HERE = "DINE_HERE",
  TAKE_OUT = "TAKE_OUT",
}

export enum Status {
  PENDING = "PENDING",
  PREPARING = "PREPARING",
  SERVED = "SERVED",
  PAID = "PAID",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  CANCELED = "CANCELED",
  REOPENED = "REOPENED",
}

export enum PaymentMethod {
  CASH = "CASH",
  CREDIT_CARD = "CREDIT_CARD",
  DEBIT_CARD = "DEBIT_CARD",
}